// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_pecha/test/features/auth/presentation/providers/auth_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_pecha/core/error/failures.dart' as _i5;
import 'package:flutter_pecha/core/network/connectivity_service.dart' as _i17;
import 'package:flutter_pecha/features/auth/domain/entities/auth_credentials.dart'
    as _i6;
import 'package:flutter_pecha/features/auth/domain/usecases/clear_guest_mode_and_onboarding_usecase.dart'
    as _i16;
import 'package:flutter_pecha/features/auth/domain/usecases/clear_guest_mode_usecase.dart'
    as _i14;
import 'package:flutter_pecha/features/auth/domain/usecases/continue_as_guest_usecase.dart'
    as _i12;
import 'package:flutter_pecha/features/auth/domain/usecases/get_credentials_usecase.dart'
    as _i11;
import 'package:flutter_pecha/features/auth/domain/usecases/has_valid_credentials_usecase.dart'
    as _i10;
import 'package:flutter_pecha/features/auth/domain/usecases/initialize_auth_usecase.dart'
    as _i8;
import 'package:flutter_pecha/features/auth/domain/usecases/is_guest_mode_usecase.dart'
    as _i13;
import 'package:flutter_pecha/features/auth/domain/usecases/login_usecase.dart'
    as _i2;
import 'package:flutter_pecha/features/auth/domain/usecases/logout_usecase.dart'
    as _i15;
import 'package:flutter_pecha/shared/domain/base_classes/usecase.dart' as _i9;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i2.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.AuthCredentials>> call(
    _i2.LoginParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.AuthCredentials>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.AuthCredentials>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.AuthCredentials>>);
}

/// A class which mocks [InitializeAuthUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockInitializeAuthUseCase extends _i1.Mock
    implements _i8.InitializeAuthUseCase {
  MockInitializeAuthUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(_i9.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [HasValidCredentialsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockHasValidCredentialsUseCase extends _i1.Mock
    implements _i10.HasValidCredentialsUseCase {
  MockHasValidCredentialsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, bool>> call(_i9.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, bool>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, bool>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, bool>>);
}

/// A class which mocks [GetCredentialsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCredentialsUseCase extends _i1.Mock
    implements _i11.GetCredentialsUseCase {
  MockGetCredentialsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.AuthCredentials>> call(
    _i9.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.AuthCredentials>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.AuthCredentials>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.AuthCredentials>>);
}

/// A class which mocks [ContinueAsGuestUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockContinueAsGuestUseCase extends _i1.Mock
    implements _i12.ContinueAsGuestUseCase {
  MockContinueAsGuestUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(_i9.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [IsGuestModeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsGuestModeUseCase extends _i1.Mock
    implements _i13.IsGuestModeUseCase {
  MockIsGuestModeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, bool>> call(_i9.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, bool>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, bool>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, bool>>);
}

/// A class which mocks [ClearGuestModeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockClearGuestModeUseCase extends _i1.Mock
    implements _i14.ClearGuestModeUseCase {
  MockClearGuestModeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(_i9.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i15.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(_i9.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [ClearGuestModeAndOnboardingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockClearGuestModeAndOnboardingUseCase extends _i1.Mock
    implements _i16.ClearGuestModeAndOnboardingUseCase {
  MockClearGuestModeAndOnboardingUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(
    _i16.ClearGuestModeAndOnboardingParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i17.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  _i3.Stream<bool> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i3.Stream<bool>.empty(),
          )
          as _i3.Stream<bool>);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}